dependencies:
- name: elasticsearch
  version: ^1.22.0
  repository: file:///home/alex/Documents/github/charts/stable/elasticsearch
  condition: elasticsearch.enabled
- name: kibana
  version: ^3.0.0
  repository: file:///home/alex/Documents/github/charts/stable/kibana
  condition: kibana.enabled
- name: filebeat
  version: ^3.1.1
  repository: file:///home/alex/Documents/github/charts/stable/filebeat
  condition: filebeat.enabled
- name: logstash
  version: ^2.4.0
  repository: file:///home/alex/Documents/github/charts/stable/logstash
  condition: logstash.enabled
- name: fluentd
  version: ^2.3.2
  repository: file:///home/alex/Documents/github/charts/stable/fluentd
  condition: fluentd.enabled
- name: fluent-bit
  version: ^2.8.5
  repository: file:///home/alex/Documents/github/charts/stable/fluent-bit
  condition: fluent-bit.enabled
- name: fluentd-elasticsearch
  version: ^2.0.7
  repository: file:///home/alex/Documents/github/charts/stable/fluentd-elasticsearch
  condition: fluentd-elasticsearch.enabled
- name: nginx-ldapauth-proxy
  version: ^0.1.0
  repository: file:///home/alex/Documents/github/charts/stable/nginx-ldapauth-proxy
  condition: nginx-ldapauth-proxy.enabled
- name: elasticsearch-curator
  version: ^2.1.3
  repository: file:///home/alex/Documents/github/charts/stable/elasticsearch-curator
  condition: elasticsearch-curator.enabled
- name: elasticsearch-exporter
  version: ^2.1.1
  repository: file:///home/alex/Documents/github/charts/stable/elasticsearch-exporter
  condition: elasticsearch-exporter.enabled
